PROXMOX_USERNAME: ENC[AES256_GCM,data:lMIbr6iAc3rjB30kwakP,iv:aOQsEKXDri00lqrrGFeuXXGdP1jEmV5NGKW2mW98kYk=,tag:WD0u9ZlWy1rqyB02dWY/Uw==,type:str]
PROXMOX_TOKEN: ENC[AES256_GCM,data:AROtEjCl3ls+hxYzTJnipJuDLu+KtiQoNSm2j/DpPoqmAjHJ,iv:+Zw8QK3tHbTOwbfOjG0XVz70AXbZGLwL9dxMd1Bh1Is=,tag:xZHveW4tXyMgcT7NI4c3pA==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR2VUSk1sSUJBWml6VWFJ
            UE02Nkg3anlqWWZ6TkRzcEZvUFE3aTVnSXhRCk45ZjNwVzJmdG1BNnlGdHFQNmNX
            S3lJVndLOTduNE13cU9qMUE1Y0JaUWsKLS0tIGpqbGJTSmZ4T2dCLzV0ZkYxaDRp
            MkFQdXlpY2sxNFpDWmMrQTlkMG1nR3MK9T06Wi5UdtJkvmhrChNWHxIffR9qscSC
            6k+uOm8A8PXNKDsOCBsa61KDqIxHiwE3olglKNDtvTJzI71Uw9zpQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T15:02:58Z"
    mac: ENC[AES256_GCM,data:wxoyqcR42DCsEBplE7cpZJ29IEhf0OXFGsc3+1YFGyhBeEv2+44qkLhW2pMmtSCo4qsAcoKdLO9eunyjVVIyUonhmj2SXJqjU+MmTJAgC2hFqcUkCI/2dOqiZKWeqa4fPQiV1lLqelK4tmvlfj25nlqi1ZI29rfynhwe9l4BluA=,iv:EcADGt+dcdkdPwW+L/hNIzgcz8ORh4J7BaTmn5rYVd8=,tag:yKrb2JKb2oi3PZBB5NwVow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
