PKR_VAR_proxmox_token: ENC[AES256_GCM,data:Ub+h03hqDRyAIb57tW9MR/bbg3/WNj329H2ucB4K2ywtspi1,iv:ulZZ1vDPOGRJS5TPbzHOiJtl81fP7P4X++i7EFJFXzs=,tag:T+v8lMdlOIw/5tl6Y0ismA==,type:str]
PKR_VAR_proxmox_user: ENC[AES256_GCM,data:gPXJN5hZy1e8+AQDXJaG,iv:zsc1XtTYSGmGjjCUVUPz9Me4oGZtwAGKHxtLamHmPLU=,tag:36wn8omwFLsT8LUxB5WywA==,type:str]
ADMIN_PRIVATE_KEY: ENC[AES256_GCM,data:lyT/ZcaRktPn5OO0l7hOto/8l15kSL4Ea/q82b//jWuP5vKrg/+hUx9gHh0glCtOmrFTZQDS9fy3AFMCi1KIyYbVGBvvqUHg79808QL1d0vdDW4/pxcZ5ofMRenyr4bTZ6YJafKHC1VtbRhrc7YAKzOHI/KFLT3A/9COqnKjh7/9bM0EEKSBIC2xw3yd3ssnoils5t9vpWNKwpbp3BjPOY8UyDsRg9dL7oETXlCpWKZHLt342zincONKxCnLMWtRIgNRtx/vnVFWaNOWi4lOJp2DxnDl2Cs3y21v5Byqa9XwR2tliwMkckltLhPrKRmDUXkP0pa6EfkTnUYBTubz+KiTIIm7pAgZoi1RIL42pKbvZ/EKBU4/5lcaIHwKB9KjOAggt6WEB2g3sH8FGlcBqCZzMCjwe6NT4awQshdSPEaW3fefMdi5zA5IBrCW8NxrkO9EYV6F+NT3BOC7vF/8o/fDuutTnw0LnMegsDSFYbpd4PGDJ9JS+BBcVQsp5vTNGjiu+izx3ef5V02lVeMlbzSgBWXG2s6FJXa/k+I/9aP7aqVr55h25XsaPiIhIH38RvEHSrp5Uh6guwJkCX0bucsU9uyqQXR9mandKPdroaOYNG28p+b3I3p9scQzDDuOlw/cEARospY/P2H4zmpoK9EkLGq4R7WZffzQ5DLac7Ok,iv:ptqVMDjh1wgGrXhAc9O1OcP5LoOOjkgw8U8HajuT9Ow=,tag:nInriayz+sYUc6Cx70D8Rw==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR2VUSk1sSUJBWml6VWFJ
            UE02Nkg3anlqWWZ6TkRzcEZvUFE3aTVnSXhRCk45ZjNwVzJmdG1BNnlGdHFQNmNX
            S3lJVndLOTduNE13cU9qMUE1Y0JaUWsKLS0tIGpqbGJTSmZ4T2dCLzV0ZkYxaDRp
            MkFQdXlpY2sxNFpDWmMrQTlkMG1nR3MK9T06Wi5UdtJkvmhrChNWHxIffR9qscSC
            6k+uOm8A8PXNKDsOCBsa61KDqIxHiwE3olglKNDtvTJzI71Uw9zpQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T13:53:03Z"
    mac: ENC[AES256_GCM,data:k75mw1eODu1ro3OUaciT+bYzZa3M8qvxoSfUbRXXQSxqGWx/r/ptdGR899gAXbvEQCkONdD/oEcHeHe3qLEHkHeUfFBRME71bNvfmdlNFiGwzdSMCotivwlKKxEp8arSyihxK7sXywSUoGCCvn2FetZSXLJWdJEeQ1jiD5xtS5M=,iv:PdHdlWEpynsGHLA887QD1ZwBnU33tDERKMEe1U1U2PY=,tag:yA4sJhQsvLz5uCRApDGrYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
