PKR_VAR_proxmox_token: ENC[AES256_GCM,data:Ub+h03hqDRyAIb57tW9MR/bbg3/WNj329H2ucB4K2ywtspi1,iv:ulZZ1vDPOGRJS5TPbzHOiJtl81fP7P4X++i7EFJFXzs=,tag:T+v8lMdlOIw/5tl6Y0ismA==,type:str]
PKR_VAR_proxmox_user: ENC[AES256_GCM,data:gPXJN5hZy1e8+AQDXJaG,iv:zsc1XtTYSGmGjjCUVUPz9Me4oGZtwAGKHxtLamHmPLU=,tag:36wn8omwFLsT8LUxB5WywA==,type:str]
ADMIN_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:9D4Y4OgwysM18ftCxmta98+GTm8/Yd4EL6BejhmWCqet28B78JMEoPzKqbzeh04qAFv74hPyKDJZSvRoxP5352mcLsQ/OsJ53OEXNxrQQKlblCavoPmyORbuNA9TuM+wAzAuwyV1gXR/1T9MVy+fnuJTzeVj8CeJh7FXzEb9hsoK3R9lW7X9uPhc4dp/LRdPc/qAjzYkpEOJceTQZb7iizvvO+IBgdVcul/PDciODAWf4cxZAr4bu77d59g8R/hvw/lW6zXVIe90A3xoXt2myx4XcUdKL9LKyeLtdb3djhWGgYrCDMSKRNaChRpgn1MwD5Fr1BZ7NGuCaiJGHxtx3/kErYHHQZrSSrRGEUY71P045YjxIaOh7YfdVZ8xHAz6z+HTzJK7fvKrrpkPXLp6xP+b0sUviS0Hw5R2I+XbWkGBF8Bz2NtE9Ud8qWEaWrpRXv5LXec3WIyr7j20tFxJOtBrpYLMEZLJoU2D4mIDySf2/ORk+JVQQH2X1K5Vk14zTRSBjiNdR7eqDYAoldr2SpTMVO6AkV2qHaZccA7rlNUOq7KrPqNzBn6xnElDW+SRCKCrXH6yeL6ZbPYeH6GqIPc9Xb3S7LSgdKDUMva/kyTTQEpXfTBt1pNvxzk6JljghvG/5ambkVIHdXlUo5iEk33v7I0zG/IBX57nWHsRxDg8,iv:livH7xbsDjjv2Wy5OpP2+PtMLMCXupEqFGYPQYiiFfk=,tag:bFM62NAVK4DWfRSO5JTOgA==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR2VUSk1sSUJBWml6VWFJ
            UE02Nkg3anlqWWZ6TkRzcEZvUFE3aTVnSXhRCk45ZjNwVzJmdG1BNnlGdHFQNmNX
            S3lJVndLOTduNE13cU9qMUE1Y0JaUWsKLS0tIGpqbGJTSmZ4T2dCLzV0ZkYxaDRp
            MkFQdXlpY2sxNFpDWmMrQTlkMG1nR3MK9T06Wi5UdtJkvmhrChNWHxIffR9qscSC
            6k+uOm8A8PXNKDsOCBsa61KDqIxHiwE3olglKNDtvTJzI71Uw9zpQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T06:46:39Z"
    mac: ENC[AES256_GCM,data:1wekyZlCB/JlrnHsU84T4uMy0fzf08jF7uKsCZriM2oE7E665USfaJZjL4MDjKyTidxOEtxi+nMY99cL3eSoQ2Rtn+YyaALunPLXVhLcHkkTKpVcfxGZ4HpqLVDCs4w0GGZo2JthGtgIQF84FTDUgZexc+Lwe2Em5f3CeFKMNxk=,iv:NFBMyZp4RrCZGfDWgKx9Hl+tzPi5UPRoqNktBXfNpX8=,tag:fbDYcCEepl8dMRujIL519w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
