[tools]
packer = "latest"
pre-commit = "latest"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

_.file = [
  { path = "{{env.HOME}}/.env", optional = true },
  { path = ".env", optional = true },
  { path = ".creds.env.yaml", redact = true }
]
_.path = [
  "./scripts"
]

[hooks]
enter = [
  'echo ""',
  'echo "[MISE] Setup $PROJECT_NAME project..."',
  #
  'mise i -q',
  #
  'pre-commit install',
  #
  'echo "$ADMIN_SSH_PRIVATE_KEY" > keys/admin_id_ecdsa',
  'chmod 600 keys/admin_id_ecdsa'
]
